# =========================
# BASE (SEU ESTILO ANTIGO)
# =========================

fs=yes
keep-open=yes
profile=gpu-hq
hwdec=auto-safe

# =========================
# STREAM / BUFFER (IMPORTANTE)
# =========================

cache=yes
cache-secs=120
cache-pause=no

demuxer-readahead-secs=60
demuxer-max-bytes=500MiB
demuxer-max-back-bytes=200MiB

network-timeout=10

# =========================
# LEGENDAS (seu padrão antigo)
# =========================

sub-auto=fuzzy
sub-font-size=42

alang=jpn,jp,ja,en,eng
slang=pt-BR,pt,en

# =========================
# PERFORMANCE ESTÁVEL
# =========================

hwdec=auto-safe
